# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='severity',
            field=models.CharField(choices=[('1', 'Inaccuracy'), ('2', 'Mistake'), ('4', 'Blunder')], max_length=1),
        ),
        migrations.AddField(
            model_name='puzzlerating',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzler.Puzzle'),
        ),
    ]
